config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :films do
    resources :departments, only: [:new, :create]
    resources :grants, only: [:new, :create, :index]
  end

  # resources :grants, only: [:edit, :update] Good to implement

  resources :departments, only: [:show] do
    resources :tasks, only: [:new, :create]
    resources :departments_users, only: [:new, :create, :index]
    member do
      get :moodboard
    end
  end

  resources :departments, only: [:index, :destroy, :edit, :update]

  resources :tasks, except: [:new, :create] do
    member do
      patch :move
    end
    resources :submissions, only: [:new, :create]
  end



  resources :submissions, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :submissions, only: [:edit, :update, :index, :destroy]

  resources :comments, only: [:edit, :update, :index, :destroy]

  resources :users, only: [:show]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :department
  belongs_to :user
  has_many :submissions, dependent: :destroy
  acts_as_list # every time a task is created it will get its position set automatically
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_department, only: [:new, :create]

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.department = @department
    @task.user = current_user
    if @task.save
      redirect_to department_path(@department)
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    @submissions = @task.submissions
    @department = @task.department
  end

  def index
    @tasks = Task.all
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @department = @task.department
    redirect_to department_path(@department) #this was task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    @department = @task.department
    redirect_to department_path(@department)
  end

  def move
    @task = Task.find(params[:id])
    @task.insert_at(params[:position].to_i)
    @task.update(status: params[:status])
    head :ok
  end

  private

  def get_department
    @department = Department.find(params[:department_id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :status, :due_date)
  end

end

app/views/tasks/_show.html.erb
<div class="task-show-main-container">
  <div class="task-show-container">
    <div class="inner-task-show-container">

      <div class="close-modal">
        <p> x </p>
      </div>
      <div class="task-show-title">
        <div class ="task-show-title-sub">
          <h2> <%= task.title.capitalize %> </h2>
        </div>
        <div class ="task-show-title-sub">
          <div class = "task-show-edit">
            <%= link_to 'Edit', edit_task_path(task), class: "task-show-title-sub-link" %>
          </div>
          <div class = "task-show-delete">
            <%= link_to 'Delete', task_path(action: :delete,id: task.id),method: :delete, data: {confirm: "Are you sure?"}, class: "task-show-title-sub-link" %>
          </div>
        </div>
      </div>
      <div class="task-show-task-type">
        <div class="task-show-label">
          <p> 📅 Due date </p>
        </div>
        <div class="task-show-value">
          <% if task.due_date !=""%>
            <p> <%= task.due_date%> </p>
          <% else %>
            <p> not available </p>
          <% end %>
        </div>
      </div>
      <div class="task-show-task-type">
        <div class="task-show-label">
          <p> 🤔 Status </p>
        </div>
        <div class="task-show-value">
          <% if task.status == "to-do"%>
            <p> 🔴 <%= task.status  %> </p>
          <% elsif task.status == "in-progress"%>
            <p> 🟠 <%= task.status  %> </p>
          <% else task.status == "done"%>
            <p> 🟢 <%= task.status  %> </p>
          <%end%>
        </div>
      </div>
      <div class="task-show-task-type">
        <div class="task-show-label">
          <p> 👤 Assignee </p>
        </div>
        <div class="task-show-value">
          <p> <%= task.user.first_name %>  </p>
        </div>
      </div>
      <div class="task-show-task-type">
        <div class="task-show-label">
          <p> 🖇️ Description </p>
        </div>
        <div class="task-show-value content-box"></div>
      </div>
      <div class = "description-box">
        <div class="task-show-value content-box">
          <% if task.content == '' %>
            <p><em> / a description </em> </p>
          <% else %>
            <%= task.content %>
          <%end%>
        </div>
      </div>
      <div class="task-show-task-type">
        <div class="add-submission-btn">
          <%= link_to '+ Add submission', new_task_submission_path(task) %>
        </div>
      </div>

      <div class="task-show-submissions-main">
          <br> <strong> <small> All submissions </small> </strong>
        <div class="task-show-submissions">
            <% task.submissions.each do |submission|%>
              <%= link_to submission_path(submission) do %>
                <div class = "single-submission">
                  <div>
                    <% if current_user.photo.present? %>
                      <%= cl_image_tag current_user.photo.key, class: "avatar-comment"%>
                    <% else %>
                      <%= image_tag "stock-profile.jpg", class: "avatar-comment" %>
                  <% end %>
                  </div>
                  <div class = "single-submission-content">
                    <%= submission.title %> <br>
                    <small> Submitted by <%= submission.user.first_name.capitalize %> <%=submission.user.last_name.capitalize %> on <i> on <%= submission.created_at.strftime("%a %b %e at %l:%M %p") %> </i> </small>
                  </div>
                </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_taskshow.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="task-new-card">
          <div class="task-center">
            <div class="task-title">
            <h2> <%= @task.title %> </h2>
            </div>
            <div class="task-content">
            <p> <%= @task.content%> </p>
            </div>
            <div class="task-status">
           <p> <%= @task.status %> 🔴 </p>
            </div>
            <%# <div class="glass-button" href="#">Submit %>
          <%=link_to "Back to tasks", new_department_task_path(@department) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row justify-content-container">
    <div class="edit-task-card-container">
      <div class="edit-task-card">
       <h3> Edit your task </h3>
        <%= simple_form_for(@task) do |f| %>
          <%= f.input :title %>
          <%= f.input :content%>
          <%= f.input :due_date %>
          <%= f.input :status, :collection => %w[to-do in-progress done] %>
          <%= f.submit class: "new-film-btn" %>
        <% end %>
       </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
   <div class="row justify-content-center">
     <div class="col-12 col-sm-4">
       <div class="task-new-card">
           <div class="task-center">
           <%= simple_form_for([@department, @task]) do |f| %>
             <div class="task-title">
              <%= f.input :title %>
             </div>
             <div class="task-content">
              <%= f.input :content %>
             </div>
             <div class="task-status">
              <%= f.input :status, :collection => %w[to-do in-progress done] %>
             </div>
             <%= f.submit class: "new-film-btn" %>
           <% end %>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>