config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :films do
    resources :departments, only: [:new, :create]
    resources :grants, only: [:new, :create, :index]
  end

  # resources :grants, only: [:edit, :update] Good to implement

  resources :departments, only: [:show] do
    resources :tasks, only: [:new, :create]
    resources :departments_users, only: [:new, :create, :index]
    member do
      get :moodboard
    end
  end

  resources :departments, only: [:index, :destroy, :edit, :update]

  resources :tasks, except: [:new, :create] do
    member do
      patch :move
    end
    resources :submissions, only: [:new, :create]
  end



  resources :submissions, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :submissions, only: [:edit, :update, :index, :destroy]

  resources :comments, only: [:edit, :update, :index, :destroy]

  resources :users, only: [:show]
end

app/models/department.rb
class Department < ApplicationRecord
  DPTNAMES = ["Direction", "Production", "Art", "Camera", "Acting", "Electric", "Grip", "Make-Up", "Wardrobe", "Sound", "Music", "Catering", "Stunts", "VFX", "Editing"].freeze
  belongs_to :film
  has_many :tasks, dependent: :destroy
  has_many :departments_users, dependent: :destroy
  has_many :users, through: :departments_users
  has_many :grants, dependent: :destroy

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :find_film, only: [:new, :create]

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    @department.film = @film
    if @department.save
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  def show
    @department = Department.find(params[:id])
    @tasks = @department.tasks
    @film = @department.film
    @departments = Department.all

    # @depfilm = Film.find(params[:id])
    # @departments = @depfilm.departments

    @new_task = Task.new
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    @department.update!(department_params)
    redirect_to department_path(@department)
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    @film = @department.film
    redirect_to film_path(@film) # redirects to index should redirect to show page !
  end

  def moodboard
    @department = Department.find(params[:id])
    @tasks = @department.tasks
    @film = @department.film
  end

  private

  def find_film
    @film = Film.find(params[:film_id])
  end

  # def get_department
  #   @department = Department.find(params[:id])
  # end

  def department_params
    params.require(:department).permit(:name)
  end

end

app/views/departments/edit.html.erb
<%= simple_form_for(@department) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>
#add tasks & users in here too

app/views/departments/moodboard.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "Filmpod - #{@department.name}" %>


<div class="moodboard-ultra-container">
  <div class="moodboard-inner-container">

    <div class = "sidebar col-2 border-right border-secondary">
       <div class="sidebar-inner-n">
        <div class="sidebar-film-title">
          <div>
            <%=link_to @film.title, film_path(@film), class:"back-to-film-btn"%>
          </div>
        </div>

        <div class="departments-side-bar">
          <% @film.departments.each do |department| %>
          <div class="each-department-on-film-show">
              <%=link_to department.name, department_path(department)%>
          </div>
          <% end %>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Department", new_film_department_path(@film) %>
          </div>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Member", film_grants_path(@film) %>
          </div>
        </div>

        <div>
          <div class="sidebar-back-btn">
            <%= link_to 'Back', user_path %>
          </div>
          <div class="sidebar-edit-btn">
            <%= link_to 'Edit Film', edit_film_path(@film) %>
          </div>
          <div class="sidebar-danger-btn">
            <%= link_to "Delete Film", film_path(@film), method: :delete %>
          </div>
        </div>
      </div>
    </div>


    <% dptphoto = "#{@department.name}.jpg" %>
    <div class= "moodboard-main-container col-10">
      <div class="department-background-image" style= "background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,1)), url('<%= asset_path dptphoto  %>');">
        <div class="department-padding">
          <div class="department-show-tabs">
            <div class="tab-item tab-item-left">
              <%= link_to "Tasks", department_path(@department) %>
            </div>
            <div class="tab-item tab-moodboard">
              <%= link_to "Moodboard", moodboard_department_path(@department) %>
            </div>
          </div>
          <div class = "moodboard-header">
            <div class = "moodboard-header-title">
              <h1><%= @department.name.capitalize  %> Moodboard </h1>
            </div>
          </div>
        </div>
      </div>
      <div class="department-second-background">
        <div class="moodboard-container">
          <% @tasks.each do |task| %>
            <% task.submissions.each do |submission| %>
              <%= link_to submission_path(submission), class: "to-each-submission" do %>
                <div class="submission-card">
                  <% if submission.photo.present? %>
                    <%# <%= cl_image_tag submission.photos.key, class: "submission-photo" %>
                    <%= cl_image_tag submission.photo.key, class: "submission-photo" %>
                  <% else %>
                    <%= image_tag "stock-profile.jpg", class: "submission-photo" %>
                  <% end %>
                  <div class="submission-card-text">
                    <div class="submission-card-task-name">
                      <p><%= submission.title.capitalize %></p>
                    </div>
                    <% if submission.status == "submitted" %>
                      <div>
                        <p ><b style="color: rgba(184, 114, 48, 0.9);"><%= submission.status.capitalize %></b></p>
                      </div>
                    <% else %>
                      <div>
                        <p ><b style="color: rgba(62, 180, 72, 0.9);"><%= submission.status.capitalize %></b></p>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<div class="new-container">
  <div class="new-inner-container">
    <div>
      <h2>Create a New Department</h2>
      <%= simple_form_for([@film, @department]) do |f| %>
        <%# <%= f.input :name %>
        <%= f.input :name, collection: Department::DPTNAMES%>
        <div class="btndiv">
          <%= f.submit class: "new-film-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/departments/show.html.erb
<%= javascript_pack_tag 'timeline', 'data-turbolinks-track': 'reload', defer: true %>

<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "Filmpod - #{@department.name}" %>

<div class="department-showpage-container">
  <div class="department-showpage-inner-container">


    <div class = "sidebar col-2">
       <div class="sidebar-inner-n">

        <div class="sidebar-film-title">
          <div>
             <%=link_to @film.title, film_path(@film) %>
          </div>
        </div>
        <div class="departments-side-bar">
          <% @departments.each do |department| %>
            <div class="each-department-on-film-show">
                <%=link_to department.name, department_path(department)%>
            </div>
          <% end %>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Department", new_film_department_path(@film) %>
          </div>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Member", film_grants_path(@film) %>
          </div>
        </div>
        <div>
          <div class="sidebar-back-btn">
            <%= link_to 'Back', user_path %>
          </div>
          <div class="sidebar-edit-btn">
            <%= link_to 'Edit Film', edit_film_path(@film) %>
          </div>
          <div class="sidebar-danger-btn">
            <%= link_to "Delete Film", film_path(@film), method: :delete %>
          </div>
        </div>
      </div>
    </div>

    <% dptphoto = "#{@department.name}.jpg" %>

    <div class="department-showpage-main-container col-10" >
      <div class="department-background-image" style= "background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,1)), url('<%= asset_path dptphoto  %>');">
        <div class="department-padding">
          <div class="department-show-tabs">
            <div class="tab-item tab-item-left">
              <%= link_to "Tasks", department_path(@department) %>
            </div>
          <div class="tab-item tab-moodboard">
            <%= link_to "Moodboard", moodboard_department_path(@department) %>
          </div>
        </div>
        <div class="modal-container">
          <div class="modal-container-task-new-card" id="modal-container">
            <div class="close-modal">
              <p>X</p>
            </div>
            <h3> New Task </h3>
            <%= simple_form_for([@department, @new_task]) do |f| %>
              <%= f.input :title, placeholder: 'Task Title' %>
              <%= f.input :content, placeholder: 'Add a description of the task' %>
              <label for="Due-date">Due Date:</label>
              <input type="date" id="due" name="trip-start"
                     value="2021-12-03"
                     min="2021-12-03" max="2025-12-31">
              <%# <%= f.input :due_date %>
              <%= f.input :status, :collection => %w[to-do in-progress done] %>
              <%= f.submit value: "Add Task", class: "new-film-btn" %>
            <% end %>
          </div>
        </div>
        <div class = "department-showpage-header">
          <div class = "department-showpage-header-title">
            <h1><%= @department.name.capitalize  %> Department </h1>
          </div>
          <div class="link-container">
            <div class="edit-link-button">
              <%= link_to 'Edit', edit_department_path(@department)%>
            </div>
            <div class="delete-link-button">
              <%= link_to 'Delete',department_path(action: :delete,id: @department.id),method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
          </div>
        </div>
        <%# <h3> Track your progress  </h3> %>
        <div class="department-showpage-timeline-container">

          <h4> Project timeline  </h4>
          <div class = "department-showpage-timeline">
            <div class="timeline-photo">
              <%= image_tag "timeline1.png", class:"timeline-png" %>
              <div class="timeline-tasks">
                <% @tasks.each do |task| %>
                  <div class="task-on-timeline">
                    <% if task.status == "to-do" %>
                      <div class="timeline-task-point red-point" data-task-id= "<%= task.id %>"></div>
                      <div class="task-title-timeline"><%= task.title %></div>
                    <% elsif task.status == "in-progress orange-point" %>
                      <div class="timeline-task-point" data-task-id= "<%= task.id %>"></div>
                      <div class="task-title-timeline"><%= task.title %></div>
                    <% else %>
                      <div class="timeline-task-point green-point" data-task-id= "<%= task.id %>"></div>
                      <div class="task-title-timeline"><%= task.title %></div>
                    <% end %>
                  </div>
                <% end %>
                </div>

              </div>
            </div>
          </div>
        </div>
        <br>

      </div>
      <div class="department-second-background">
        <h4> Tasks ⚡️ </h4>
        <div data-controller="drag" data-drag-url="/tasks/:id/move" class="department-showpage-all-tasks-container">
          <div class="department-showpage-task-types to-do">
            <p> To-do 🔴 </p>
            <div class="department-showpage-tasks">
              <div class="single-task" id="to-do-new" data-id="0">
                <button id="new-task-btn"> + new task </button>
              </div>
              <div data-drag-target="tasks" data-status="to-do">
                <% @tasks.order(position: :asc).each do |task| %>
                  <% if task.status == "to-do"  %>
                    <div data-id="<%= task.id %>" class="single-task">
                      <button class="task-title-select"><%= task.title %></button>
                      <%= render "tasks/show", task: task %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="department-showpage-task-types in-progress">
          <p> In-progress 🟠 </p>
            <div data-drag-target="tasks" data-status="in-progress" class="department-showpage-tasks" id="itemlist">
              <% @tasks.each do |task| %>
                <% if task.status == "in-progress"  %>
                  <div data-id="<%= task.id %>" class="single-task">
                    <button class="task-title-select"><%= task.title %></button>
                      <%= render "tasks/show", task: task %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="department-showpage-task-types done">
          <p> Done 🟢 </p>
            <div data-drag-target="tasks" data-status="done" class="department-showpage-tasks">
              <% @tasks.each do |task| %>
                <% if task.status == "done"  %>
                  <div data-id="<%= task.id %>" class="single-task">
                    <button class="task-title-select"><%= task.title %></button>
                    <%= render "tasks/show", task: task %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>