config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :films do
    resources :departments, only: [:new, :create]
    resources :grants, only: [:new, :create, :index]
  end

  # resources :grants, only: [:edit, :update] Good to implement

  resources :departments, only: [:show] do
    resources :tasks, only: [:new, :create]
    resources :departments_users, only: [:new, :create, :index]
    member do
      get :moodboard
    end
  end

  resources :departments, only: [:index, :destroy, :edit, :update]

  resources :tasks, except: [:new, :create] do
    member do
      patch :move
    end
    resources :submissions, only: [:new, :create]
  end



  resources :submissions, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :submissions, only: [:edit, :update, :index, :destroy]

  resources :comments, only: [:edit, :update, :index, :destroy]

  resources :users, only: [:show]
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :task
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :photo
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :get_task, only: [:new, :create]

  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)
    @submission.task = @task
    @submission.user = current_user
    if @submission.save
      redirect_to submission_path(@submission)
    else
      render :new
    end
  end

  def show
    @submission = Submission.find(params[:id])
    @task = @submission.task
    @submission.user = current_user
    @comment = Comment.new
    @department = @task.department
    @film = @department.film
    @departments = @film.departments
  end

  def edit
    @submission = Submission.find(params[:id])
  end

  def update
    @submission = Submission.find(params[:id])
    @submission.update(submission_params)
    @task = @submission.task
    redirect_to submission_path(@submission)
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    @task = @submission.task
    redirect_to task_path(@task)
  end

  private

  def get_task
    @task = Task.find(params[:task_id])
  end

  def submission_params
    params.require(:submission).permit(:title, :content, :photo, :status)
  end

end

app/views/submissions/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="edit-submission-card-container">
      <div class="edit-submission-card">
        <h3> Edit your submission </h3>
          <%= simple_form_for(@submission) do |f| %>
            <%= f.input :title %>
            <%= f.input :content%>
            <%= f.input :photo, as: :file %>
            <%= f.input :status, :collection => %w[approved], as: :radio_buttons %>
            <%= f.submit class: "new-film-btn" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/submissions/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="new-submission-card-container">
      <div class="new-submission-card">
        <h3> New Submission</h3>
          <%= simple_form_for ([@task, @submission]) do |f| %>
            <%= f.input :title, placeholder: 'Submission Title' %>
            <%= f.input :content, placeholder: 'Describe your submission here' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit value:"Submit", class: "new-film-btn" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/submissions/show.html.erb
<div class="submission-show-main-container">
  <div class="submission-show-container">
    <div class = "sidebar col-2">
       <div class="sidebar-inner-n">

        <div class="sidebar-film-title">
          <div>
            <%=link_to @film.title, film_path(@film), class:"back-to-film-btn"%>
          </div>
        </div>
        <div class="departments-side-bar">
          <% @departments.each do |department| %>
            <div class="each-department-on-film-show">
                <%=link_to department.name, department_path(department)%>
            </div>
          <% end %>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Department", new_film_department_path(@film) %>
          </div>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Member", film_grants_path(@film) %>
          </div>
        </div>
        <div>
          <div class="sidebar-back-btn">
            <%= link_to 'Back', user_path %>
          </div>
          <div class="sidebar-edit-btn">
            <%= link_to 'Edit Film', edit_film_path(@film) %>
          </div>
          <div class="sidebar-danger-btn">
            <%= link_to "Delete Film", film_path(@film), method: :delete %>
          </div>
        </div>
      </div>
    </div>

    <div class="submission-show-inner-container col-10">
        <div class ="submission-show-title sub">
          <p> Submission for the task: <strong> "<%= @submission.task.title %>" </p> </strong>
          <div class= "submission-show-back">
          <%# <%= link_to 'back to task', :back %>
            <%= link_to 'Back to task', department_path(@submission.task.department), class: "submission-show-title sub " %>
          </div>
        </div>
        <div class="submission-show-title">
          <div class ="submission-show-title sub">
            <h2> <%= @submission.title.capitalize %> </h2>
          </div>
          <div class ="submission-show-title sub">
            <div class = "submission-show-edit">
              <%= link_to 'Edit', edit_submission_path(@submission) %>
            </div>
            <div class = "submission-show-delete">
              <%= link_to 'Delete',submission_path(action: :delete,id: @submission.id),method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
          </div>
        </div>

        <div class = "submission-show-all-details">
          <div class = "submission-show-details-1">
            <div class="submission-show-submission-type">
              <div class="submission-show-label">
                <p> 📅 Submission date </p>
              </div>
              <div class="submission-show-value">
                <p> <%= @submission.created_at.strftime("%b %d, %Y") %> </p>
              </div>
            </div>

            <div class="submission-show-submission-type">
              <div class="submission-show-label">
                <p> 🤔 Status </p>
              </div>
              <div class="submission-show-value">
                <% if @submission.status == "submitted" %>
                    <p> 🟠 <%= @submission.status.capitalize  %>  </p>
                <% else @submission.status == "approved" %>
                    <p> 🟢 <%= @submission.status.capitalize  %>  </p>
                <%end%>
              </div>
            </div>

            <div class="submission-show-submission-type">
              <div class="submission-show-label">
                <p> 👤 Submitted by  </p>
              </div>
              <div class="submission-show-value">
                <p> <%= @submission.user.first_name.capitalize %> </p>
              </div>
            </div>

            <div class="submission-show-submission-type">
              <div class="submission-show-label">
                <p> 🖇 Description </p>
              </div>
              <div class="submission-show-value content-box">
              </div>
            </div>
            <div class = "description-box">
              <div class="submission-show-value content-box">
                <% if @submission.content == "" %>
                  <p><em> Add a description </em> </p>
                <% else %>
                  <%= @submission.content %>
                  <%end%>
                </p>
              </div>
            </div>
            <div class= "comments-section-main-container">
              <div class = "comments-section-inner-container"
                data-controller="submission-subscription"
                data-submission-subscription-submission-id-value="<%= @submission.id
                %>" >
                <small>  Comments  </small>
              <% @submission.comments.each do |comment| %>
            <div class = "single-comment">
              <%= render "comments/comment", comment: comment %>
            </div>
            <% end %>
          </div>

          <div class = "new-comment">

            <div>
              <% if current_user.photo.present? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar-comment"%>
              <% else %>
              <%= image_tag "stock-profile.jpg", class: "avatar-comment" %>
             <% end %>
            </div>

            <div class ="new-comment content">
              <%= simple_form_for [@submission, @comment], remote: true do |f| %>
                <%= f.input :content, label: false, placeholder: "Add a comment for ##{@submission.title}" %>
                <%= f.submit class: "comment-btn", value: "Comment" %>
              <% end %>
            </div>
          </div>

        </div>
          </div>
          <div class = "submission-show-details-2">
            <% if @submission.photo.present? %>
              <%= cl_image_tag @submission.photo.key, class: "submission-show-picture"%>
            <% else %>
              <p> <em> no image was submitted </em> <p>
             <% end %>
          </div>
        </div>

   </div>
  </div>
</div>