config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :films do
    resources :departments, only: [:new, :create]
    resources :grants, only: [:new, :create, :index]
  end

  # resources :grants, only: [:edit, :update] Good to implement

  resources :departments, only: [:show] do
    resources :tasks, only: [:new, :create]
    resources :departments_users, only: [:new, :create, :index]
    member do
      get :moodboard
    end
  end

  resources :departments, only: [:index, :destroy, :edit, :update]

  resources :tasks, except: [:new, :create] do
    member do
      patch :move
    end
    resources :submissions, only: [:new, :create]
  end



  resources :submissions, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :submissions, only: [:edit, :update, :index, :destroy]

  resources :comments, only: [:edit, :update, :index, :destroy]

  resources :users, only: [:show]
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :departments, dependent: :destroy
  has_many :grants, dependent: :destroy
  has_many :users, through: :grants

  has_one_attached :photo

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films =Film.all
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    if @film.save!
      Grant.create!(user: current_user, film: @film, rank_level: "Direction", department: Department.first)
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  def show
    @film = Film.find(params[:id])
    @departments = @film.departments
    @users = @film.users
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])
    @film.update(film_params)

    redirect_to film_path(@film)
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    redirect_to user_path
  end

  private

  def film_params
    params.require(:film).permit(:title, :synopsis, :genre, :estimated_release_date, :photo)
  end

end

app/views/films/edit.html.erb
<%= simple_form_for(@film) do |f| %>
  <%= f.input :title %>
  <%= f.input :synopsis %>
  <%= f.input :genre %>
  <%= f.input :estimated_release_date %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', film_path(@film) %>

app/views/films/index.html.erb
<h1>My Films</h1>
<div>
  <% @films.each do |film| %>
    <%= link_to film.title, film_path(film)  %>
  <% end %>
</div>
<%= link_to 'Create', new_film_path %>

app/views/films/new.html.erb
<div class="new-container">
  <div class="new-inner-container">
    <div>
      <h2>Create a New Project</h2>
      <%= simple_form_for(@film) do |f| %>
          <%= f.input :title, class: "new-input"%>
          <%= f.input :synopsis, class: "new-input" %>
          <%= f.input :genre, class: "new-input" %>
          <%= f.input :estimated_release_date, class: "new-input" %>
          <%= f.input :photo, as: :file %>
          <div class="btndiv">
            <%= f.submit class: "new-film-btn" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/films/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "Filmpod - #{@film.title}" %>

<div class="film-moodboard-container">
  <div class="film-moodboard-inner-container">
    <div class="sidebar col-2 border-right border-secondary ">
      <div class="sidebar-inner-n">
        <div class="sidebar-film-title">
          <div>
            <%=link_to @film.title, film_path(@film) %>
          </div>
        </div>

        <div class="departments-side-bar">
          <% @departments.each do |department| %>
          <div class="each-department-on-film-show">
              <%=link_to department.name, department_path(department)%>
          </div>
          <% end %>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Department", new_film_department_path(@film) %>
          </div>
          <div class="add-dpt-btn">
            <%= link_to "+ Add Member", film_grants_path(@film) %>
          </div>
        </div>

        <div class="dangerzone">
          <div class="sidebar-back-btn">
            <%= link_to 'Back', user_path %>
          </div>
          <div class="sidebar-edit-btn">
            <%= link_to 'Edit Film', edit_film_path(@film) %>
          </div>
          <div class="sidebar-danger-btn">
            <%= link_to "Delete Film", film_path(@film), method: :delete %>
          </div>
        </div>
      </div>
    </div>

    <div class="film-moodboard-main col-10">
      <div class="film-moodboard-card-container">
        <% @departments.each do |department| %>
          <%=link_to department_path(department), class:"btn-card" do %>
            <% dptphoto = "#{department.name}.jpg" %>
            <div class="film-moodboard-card-1" style= "background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('<%= asset_path dptphoto  %>');" >

              <h3><%= department.name %></h3>
            </div>
          <% end %>
        <% end %>
        <%# <div class="film-moodboard-card-1">
          <h3>Music Department</h3>
        </div>
        <div class="film-moodboard-card-2">
          <h3>Costumes</h3>
        </div>
        <div class="film-moodboard-card-3">
          <h3>Sets</h3>
        </div>
        <div class="film-moodboard-card-4">
          <h3>Photography</h3>
        </div>
        <div class="film-moodboard-card-5">
          <h3>Make-up Department</h3>
        </div>
        <div class="film-moodboard-card-6">
          <h3>Sound Department</h3>
        </div> %>
      </div>
    </div>
  </div>
</div>